AllCops:
  NewCops: enable
  TargetRubyVersion: 4.0

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false